name: Deploy KitchenOS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Backend Dependencies
        working-directory: ./kitchenos-backend
        run: npm install

      - name: Generate Prisma Client
        working-directory: ./kitchenos-backend
        run: npx prisma generate

      - name: Build Backend
        working-directory: ./kitchenos-backend
        run: npm run build

      - name: Install Frontend Dependencies
        working-directory: ./kitchenos-frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./kitchenos-frontend
        run: npm run build
